apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: risky-cluster-admin
subjects:
- kind: User
  name: risky-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io