apiVersion: v1
kind: Pod
metadata:
  name: app-security
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: app-security
    image: vish/stress
    command: [ "sh", "-c", "sleep 1h" ]
  resources:
    limits:
      memory: "200Mi"
      cpu: "1"
    requests:
      memory: "100Mi"
      cpu: "0.5"
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]