name: Trivy Scan

on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
          version: v0.48.2

    - name: Run Trivy config scan
      run: |
          trivy fs ~/src/github.com/maan134/k8s-trivy-cb/tree/main/k8s-files
          trivy config --format sarif --output trivy-results.sarif . || true
    - name: Upload SARIF as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: trivy-report
          path: trivy-results.sarif
          
    - name: Send Trivy report to external server
      run: |
          curl -v -X POST -H "Content-Type: multipart/form-data" -F "file=@trivy-results.sarif" http://3rvz2umdy425l4q0hh4kj.appsecengineer.training:8880/callback

    #- name: Run Trivy vulnerability scanner in repo mode
    #  uses: aquasecurity/trivy-action@master
    #  with:
    #    scan-type: 'fs'
    #    scan-ref: '.'
    #    scanners: 'vuln,secret,misconfig'
    #    ignore-unfixed: true
    #    format: 'sarif'
    #    output: 'trivy-results.sarif'
    #    skip-setup-trivy: true


    
